### ISSUE TITLE
Feature Request: Mute toggle & Mute feedback support

### ISSUE THREAD

**Issue by cgarwood** [bitfocus/companion-module-behringer-x32#6]
Is it possible to add the option to toggle a mute group on/off? In the current builds it looks like you can only have a button mute a group/channel and have to use a separate button to unmute the group/channel. I'd love to have a button that could toggle it to the opposite of whatever it currently is on the board.

Likewise, feedback support would be great so we could change the colors of the button when a group/channel is muted.

**Comment by jgastonraoul** [comment]
I agree with the feedback feature request !

**Comment by krocheck** [comment]
Feedback for OSC over UDP, which is how X32 and it's variants communication, is currently not possible because of a core implementation that needs to happen related to opening receive ports and enabling routing to the appropriate instances.  As currently implemented, if you had 2 X32 instances or 2 OSC devices that use the same receive port, the first would open the port and the second would receive a socket in use error when trying to open its receive port. So we need an abstraction to allow this.  Its been on the list and discussed, but no movement yet.

**Comment by nottooloud** [comment]
I'm not at an X32 right now, but if you set the button to Latch/Toggle, and then set a Key Down/On Action with Mute selected, and a Key Up/Off Action on the same button with Unmute selected, it should toggle.

**Comment by Julusian** [comment]
This feedback type is implemented in latest 2.0
